### ISSUE TITLE
IDE adding characters to my work causing test to fail and making debugging impossible

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/oo-email-parser#11]
All kinds of issues wit the IDE, kept dropping out of reverting my work to previously saved version, up to 40 minutes old, then started adding characters and lines to my work.  Had all kinds of frustrating hours before I finally realized what I was submitting was repeatedly being altered or reverted to previous changes.

This is what I am submitting:
require 'pry'

class EmailParser
  attr_accessor :email_string
  
  def initialize(email_string)
    @email_string = email_string
  end  
  
  def parse
  @email_string = @email_string.split(/[\s,']/)
  @email_string.reject! {|x| x.empty?}
  @email_string.uniq  
  end  

end  

And this is what it is changing it to:

require 'pry'

# Build a class EmailParser that accepts a string of unformatted 
# emails. The parse method on the class should separate them into
# unique email addresses. The delimiters to support are commas (',')
# or whitespace (' ').
class EmailParser
  attr_accessor :email_string
<<<<<<< HEAD
=======
  @@emails = []
>>>>>>> c53f3e252a06ed52e84132d9a2513a629cb54aca
  
  def initialize(email_string)
    @email_string = email_string
  end  
  
  def parse
<<<<<<< HEAD
  @email_string = @email_string.split(/[\s,']/)  
  @email_string.delete_if {|c| c.empty?}
  @email_string.uniq
  end  

end  
    
=======
      @email_string = @email_string.split(/[\s,]/)
      @email_string.reject! {|x| x.empty?}
      @email_string.uniq 
  end 
end  
    
  
>>>>>>> c53f3e252a06ed52e84132d9a2513a629cb54aca

**Comment by curiositypaths** [comment]
Thanks for [contributing](http://help.learn.co/improving-learn) to the [Learn](http://learn.co/) curriculum!

Bear in mind that [raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform. The first place to turn for most issues is the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) feature on [Learn](http://learn.co/). For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

### Suggesting new curriculum 📝
If you have suggestions for new content that you think would improve the flow or coverage of the Learn curriculum, that's awesome, but keep the following in mind:
- The curriculum is not intended to be an exhaustive suite that covers every single topic in Ruby, JavaScript, etc.
- It might be a good idea to first check with the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) and/or peers who recently completed the same material to see if they noticed similar deficiencies.

### Reporting bugs 🐛
If you'd like to [report a bug](http://help.learn.co/improving-learn/reporting-bugs/reporting-a-bug) about the [Learn IDE](http://help.learn.co/the-learn-ide), the [lights not working on Learn](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green), or any other issue with the site, please consult the [Learn Help Center](http://help.learn.co/) and/or escalate the issue via [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). If you are unable to access Ask a Question or your track is not supported by the Technical Coaches, please send us a message via the [Intercom](https://user-images.githubusercontent.com/17556281/27602126-b825ff3a-5b3f-11e7-9dcd-0ced7e507bfb.png) widget on any [Help Center](http://help.learn.co/) page.

As always thank you for contributing 💙

**Comment by atxrenegade** [comment]
That's great but I have no idea how this issue was raised on git hub. The only place I mentioned it was on the Learn IDE. The error did occured directly after a commit, so Im guessing this was part of the bug.

**Comment by atxrenegade** [comment]
I was not aware that one was raised, but my issue did occur immediatly after a commit, this looks like what I wrote in the LearnIDE on ask a question, I may have mistakenly created one.

**Comment by atxrenegade** [comment]
When I first saw this, I thought this was part of the glitch because my issue occured directly after and related to my git lesson commit, and I only recalled use the learn ide to address it, but now after looking at it closer I remember using this as alternate method when I couldnt fit my issue into the alotted 255 characters.
