### ISSUE TITLE
The solution on github is outdated

### ISSUE THREAD

**Issue by AlexCodeBigBlue** [learn-co-curriculum/oo-email-parser#13]
The solution only accounts for splitting on "," and not the current instructions to work for addresses separated by only white spaces as well as ones separated by commas

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
