### ISSUE TITLE
The test asks for EmailAddressParses

### ISSUE THREAD

**Issue by dwandrew** [learn-co-curriculum/oo-email-parser#15]
Hi there,

The test for this lab asks for EmailAddressParses, but the notes say to call it EmailParser not a bit issue, but through i would raise it

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
