### ISSUE TITLE
In the directions we just mention that you'll get a list with commas, but the tests check for commas or spaces

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/oo-email-parser#4]
It's in a random hint lower down, but should be part of the description

**Comment by joshuabamboo** [comment]
Looks like it's in the description as well: 

"You should be able to initialize with a list of emails either separated with spaces or separated with commas."

**Comment by AnnJohn** [comment]
@joshuabamboo @jmburges can we close this issue?

**Comment by joshuabamboo** [comment]
Yes, looks good to me. @AnnJohn
