### ISSUE TITLE
parser? or parse

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/oo-email-parser#7]
Encountered this while trying to pass lab:

Is it `#parser` or `#parse` that we are supposed to write? The errors I got related to 'parse`

**Comment by AnnJohn** [comment]
Hi @CodeByLine it should be #parse. However for questions related to how to solve a lab, please use the Ask a Question tool. Issues here are for specific problems with the curriculum that we'll need to update. Thanks!
